# Generated by Django 6.1.1 on 2026-09-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('WIRE', 'Wire'), ('PRESS_RELEASE', 'Press Release'), ('BLOG', 'Blog'), ('SOCIAL', 'Social')], max_length=20)),
                ('handle', models.CharField(blank=True, max_length=50)),
                ('trust_tier', models.PositiveSmallIntegerField(default=3)),
                ('homepage', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['trust_tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('ingest_method', models.CharField(choices=[('FILE', 'File'), ('IMAGE', 'Image / Screenshot'), ('MANUAL', 'Manual')], default='FILE', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingest/images/')),
                ('extraction_notes', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('UNTRIAGED', 'Untriaged'), ('CLUSTERED', 'Clustered'), ('SPIKED', 'Spiked')], db_index=True, default='UNTRIAGED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ingest.source')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
