# Generated by Django 6.1.1 on 2026-09-08 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(db_index=True, max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BriefRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('MACHINE_DRAFT', 'Machine Draft'), ('REPORTER_EDIT', 'Reporter Edit'), ('EDITOR_EDIT', 'Editor Edit'), ('CORRECTION', 'Correction'), ('MERGE_NOTE', 'Merge Note')], max_length=16)),
                ('change_note', models.CharField(blank=True, max_length=500)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published'), ('SPIKED', 'Spiked')], db_index=True, default='NEW', max_length=12)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('clustered_by', models.CharField(choices=[('AUTO', 'Auto'), ('LLM', 'LLM'), ('HUMAN', 'Human')], default='AUTO', max_length=6)),
                ('cluster_confidence', models.FloatField(blank=True, null=True)),
                ('first_item_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stories', to=settings.AUTH_USER_MODEL)),
                ('canonical_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_into_me', to='desk.story')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('SUPERSEDED', 'Superseded'), ('CORRECTED', 'Corrected')], default='LIVE', max_length=12)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='desk.briefrevision')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='desk.story')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('was_published_at_merge', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='desk.story')),
                ('into_story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_into', to='desk.story')),
            ],
        ),
        migrations.AddField(
            model_name='briefrevision',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='desk.story'),
        ),
        migrations.AlterUniqueTogether(
            name='briefrevision',
            unique_together={('story', 'version')},
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('detached_at', models.DateTimeField(blank=True, null=True)),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_items', to='ingest.rawitem')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_items', to='desk.story')),
            ],
            options={
                'ordering': ['attached_at'],
                'unique_together': {('story', 'item')},
            },
        ),
    ]
